const ActionTypes = {
        // auth action types
        USER_REGISTRATION_SUCCESS: "USER_REGISTRATION_SUCCESS",
        USER_REGISTRATION_FAIL: "USER_REGISTRATION_FAIL",
        USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
        USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
        USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
        USER_LOGOUT_FAIL: "USER_LOGOUT_FAIL",
        UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
        UPDATE_PASSWORD_FAIL: "UPDATE_PASSWORD_FAIL",
        UPDATE_PIN_SUCCESS: "UPDATE_PIN_SUCCESS",
        UPDATE_PIN_FAIL: "UPDATE_PIN_FAIL",
       
        //loading state action types
        LOADING_SHOW: "LOADING_SHOW",
        LOADING_HIDE: "LOADING_HIDE",
       
        //verification action types
        MAIL_EXIST_SUCCESS: "MAIL_EXIST_SUCCESS",
        MAIL_EXIST_FAIL: "MAIL_EXIST_FAIL",
        PHONE_EXIST_SUCCESS: "PHONE_EXIST_SUCCESS",
        PHONE_EXIST_FAIL: "PHONE_EXIST_FAIL",

        //fetch action types
        FETCH_COUNTRIES_SUCCESS: "FETCH_COUNTRIES_SUCCESS",
        FETCH_COUNTRIES_FAIL: "FETCH_COUNTRIES_FAIL",
        FETCH_STATES_SUCCESS: "FETCH_STATES_SUCCESS",
        FETCH_STATES_FAIL: "FETCH_STATES_FAIL",

        FETCH_ALL_TRANSACTION_SUCCESS: "FETCH_ALL_TRANSACTION_SUCCESS",
        FETCH_ALL_TRANSACTION_FAIL: "FETCH_ALL_TRANSACTION_FAIL",
        FETCH_TOATAL_TRANSACTION_SUCCESS: "FETCH_TOATAL_TRANSACTION_SUCCESS",
        FETCH_TOATAL_TRANSACTION_FAIL: "FETCH_TOATAL_TRANSACTION_FAIL",
        
        
        //create/add action types
        ADD_CHARGES_SUCCESS: "ADD_CHARGES_SUCCESS",
        ADD_CHARGES_FAIL: "ADD_CHARGES_FAIL",
        ADD_PROMO_SUCCESS: "ADD_PROMO_SUCCESS",
        ADD_PROMO_FAIL: "ADD_PROMO_FAIL",
        ADD_RATE_SUCCESS: "ADD_RATE_SUCCESS",
        ADD_RATE_FAIL: "ADD_RATE_FAIL",
        ADD_BANK_SUCCESS: "ADD_BANK_SUCCESS",
        ADD_BANK_FAIL: "ADD_BANK_FAIL",
        ADD_CONVERT_SUCCESS: "ADD_CONVERT_SUCCESS",
        ADD_CONVERT_FAIL: "ADD_CONVERT_FAIL",
        ADD_TRANSACTION_SUCCESS: "ADD_TRANSACTION_SUCCESS",
        ADD_TRANSACTION_FAIL: "ADD_TRANSACTION_FAIL",
        ADD_EXISTING_BENEFICIARY_SUCCESS: "ADD_EXISTING_BENEFICIARY_SUCCESS",
        ADD_EXISTING_BENEFICIARY_FAIL: "ADD_EXISTING_BENEFICIARY_FAIL",
        ADD_NEW_BENEFICIARY_SUCCESS: "ADD_NEW_BENEFICIARY_SUCCESS",
        ADD_NEW_BENEFICIARY_FAIL: "ADD_NEW_BENEFICIARY_FAIL",
        ADD_PAYMENTS_TO_TRANSACTION_SUCCESS: "ADD_PAYMENTS_TO_TRANSACTION_SUCCESS",
        ADD_PAYMENTS_TO_TRANSACTION_FAIL: "ADD_PAYMENTS_TO_TRANSACTION_FAIL",
        CONFIRM_POLI_PAYMENTS_SUCCESS: "CONFIRM_POLI_PAYMENTS_SUCCESS",
        CONFIRM_POLI_PAYMENTS_FAIL: "CONFIRM_POLI_PAYMENTS_FAIL",
        CONFIRM_CC_PAYMENTS_SUCCESS: "CONFIRM_CC_PAYMENTS_SUCCESS",
        CONFIRM_CC_PAYMENTS_FAIL: "CONFIRM_CC_PAYMENTS_FAIL",
        UPLOAD_PAYMENTS_CONFIRMATION_SUCCESS: "UPLOAD_PAYMENTS_CONFIRMATION_SUCCESS",
        UPLOAD_PAYMENTS_CONFIRMATION_FAIL: "UPLOAD_PAYMENTS_CONFIRMATION_FAIL",
        ADD_TRANSACTION_RECEIVER_SUCCESS: "ADD_TRANSACTION_RECEIVER_SUCCESS",
        ADD_TRANSACTION_RECEIVER_FAIL: "ADD_TRANSACTION_RECEIVER_FAIL",
        
        
        //get action types
        GET_CHARGES_SUCCESS: "GET_CHARGES_SUCCESS",
        GET_CHARGES_FAIL: "GET_CHARGES_FAIL",
        GET_CHARGES_BY_PAYMENTINTYPE_SUCCESS: "GET_CHARGES_BY_PAYMENTINTYPE_SUCCESS",
        GET_CHARGES_BY_PAYMENTINTYPE_FAIL: "GET_CHARGES_BY_PAYMENTINTYPE_FAIL",
        GET_PROMOS_SUCCESS: "GET_PROMOS_SUCCESS",
        GET_PROMOS_FAIL: "GET_PROMOS_FAIL",
        GET_RATE_SUCCESS: "GET_RATE_SUCCESS",
        GET_RATE_FAIL: "GET_RATE_FAIL",
        GET_BANK_SUCCESS: "GET_BANK_SUCCESS",
        GET_BANK_FAIL: "GET_BANK_FAIL",
        GET_BUSINESS_BANK_SUCCESS: "GET_BUSINESS_BANK_SUCCESS",
        GET_BUSINESS_BANK_FAIL: "GET_BUSINESS_BANK_FAIL",
        GET_ALL_SENDING_CURRENCY_SUCCESS: "GET_ALL_SENDING_CURRENCY_SUCCESS",
        GET_ALL_SENDING_CURRENCY_FAIL: "GET_ALL_SENDING_CURRENCY_FAIL",
        GET_ALL_RECEIVING_CURRENCY_SUCCESS: "GET_ALL_RECEIVING_CURRENCY_SUCCESS",
        GET_ALL_RECEIVING_CURRENCY_FAIL: "GET_ALL_RECEIVING_CURRENCY_FAIL",
        

        //edit/update action types
        EDIT_CHARGES_SUCCESS: "EDIT_CHARGES_SUCCESS",
        EDIT_CHARGES_FAIL: "EDIT_CHARGES_FAIL",
        EDIT_PROMO_SUCCESS: "EDIT_PROMO_SUCCESS",
        EDIT_PROMO_FAIL: "EDIT_PROMO_FAIL",
        EDIT_BANK_SUCCESS: "EDIT_BANK_SUCCESS",
        EDIT_BANK_FAIL: "EDIT_BANK_FAIL",
        EDIT_RATE_SUCCESS: "EDIT_RATE_SUCCESS",
        EDIT_RATE_FAIL: "EDIT_RATE_FAIL",

        //delete action types
        DELETE_CHARGES_SUCCESS: "DELETE_CHARGES_SUCCESS",
        DELETE_CHARGES_FAIL: "DELETE_CHARGES_FAIL",
        DELETE_PROMO_SUCCESS: "DELETE_PROMO_SUCCESS",
        DELETE_PROMO_FAIL: "DELETE_PROMO_FAIL",
        DELETE_BANK_SUCCESS: "DELETE_BANK_SUCCESS",
        DELETE_BANK_FAIL: "DELETE_BANK_FAIL",
        DELETE_RATE_SUCCESS: "DELETE_RATE_SUCCESS",
        DELETE_RATE_FAIL: "DELETE_RATE_FAIL",

        //get payment purpose
        FETCH_PURPOSE_SUCCESS: "FETCH_PURPOSE_SUCCESS",
        FETCH_PURPOSE_FAIL: "FETCH_PURPOSE_FAIL",
};

export default ActionTypes;
  